### ISSUE TITLE
compilation error on rev 2d72cc7b67a7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scharada/freemedforms#376]
```
What steps will reproduce the problem?
1.  run "./build.sh -b FreeMedForms"

What is the expected output? What do you see instead?
Compilation failed:
plugins/coreplugin/settings.cpp:388:7: error: expected unqualified-id before 
‘else’
     } else {
       ^

Please provide any additional information below.
The error was introduced in rev 2d72cc7b67a7.
The following patch fix the problem:

diff --git a/plugins/coreplugin/settings.cpp b/plugins/coreplugin/settings.cpp
index d8499ec..1a489b1 100644
--- a/plugins/coreplugin/settings.cpp
+++ b/plugins/coreplugin/settings.cpp
@@ -384,7 +384,6 @@ SettingsPrivate::SettingsPrivate(QObject *parent, const 
QString &appName, const
         resourcesPath = res + "/";
         setPath(UserResourcesPath, QFileInfo(file).absolutePath());
         setPath(BundleResourcesPath, resourcesPath);
-        }
     } else {
         // RELEASE OR DEBUG INSTALLED BUILD
         if (Utils::isLinuxIntegratedCompilation()) {

```

Original issue reported on code.google.com by `hmit.pe...@gmail.com` on 17 Sep 2014 at 9:14
